articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("index", views.index, name="index"),
    path("search", views.search, name="search"),
    path("discovery", views.discovery, name="discovery"),
    path("<title>", views.article, name="full_article"),
]

customers/urls.py
from django.urls import path
from . import views

app_name = "customers"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("subscribe", views.subscribe, name="subscribe"),
    path("shop", views.shop, name="shop"),
]

lecture 7/src7/airline/airline/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('flights.urls')),
    path('admin/', admin.site.urls),
]

news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('customers.urls')),
    path('articles/', include('articles.urls', namespace="articles")),
]

articles/models.py
from django.db import models
from django_random_queryset import RandomManager

# Create your models here.
class Article(models.Model):
    objects = RandomManager()
    title = models.TextField(verbose_name='Title')
    author = models.CharField(max_length=64, verbose_name='Author', null=True)
    date = models.CharField(max_length=64, verbose_name='Publish date', null=True)
    brief = models.TextField(verbose_name='Brief', null=True)
    free_text = models.TextField(verbose_name='Free part', null=True)
    pay_text = models.TextField(verbose_name='Full part', null=True)

customers/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Customer(models.Model):
    name = models.CharField(max_length=64, verbose_name="Name", default='SOME STRING')
    sub = models.BooleanField(verbose_name="Is subscriber", default=0)
    username = models.OneToOneField(User, on_delete=models.CASCADE)
    credit_card = models.CharField(max_length=19, verbose_name="Credit card", null=True)
    card_balance = models.IntegerField(verbose_name="Balance", null=True)

    def __str__(self):
        return f"{self.name}: {self.sub}"

articles/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render
from django.db.models import Q
from .models import Article


# Create your views here.
def index(request):
    return render(request, "articles/index.html")


def search(request):
    query = request.POST["query"]
    # https://docs.djangoproject.com/en/3.0/topics/db/queries/
    # Do not need try catch
    # https://docs.djangoproject.com/en/dev/topics/db/queries/#complex-lookups-with-q-objects
    # Use Q and , | to replace AND OR
    articles = Article.objects.filter(Q(title__icontains=query) |
                                      Q(free_text__icontains=query) |
                                      Q(pay_text__icontains=query)).order_by('-id')  # Notice the - before 'id'
    context = {
        "articles": articles,
        "query": query,
    }
    return render(request, "articles/results.html", context)


def article(request, title):
    title = title.replace('-', ' ')
    article = Article.objects.get(title=title)
    context = {
        "article": article
    }
    return render(request, "articles/article.html", context)


def discovery(request):
    articles = Article.objects.filter()
    # https://github.com/rremizov/django-random-queryset
    articles = articles.random(10)
    context = {
        "articles": articles.order_by('-id'),
        "query": '',
    }
    return render(request, "articles/results.html", context)

customers/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from .models import Customer


# Create your views here.
def index(request):
    return render(request, "articles/index.html")


def login_view(request):
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("customers:index"))
        else:
            return render(request, "login.html", {"message": "Invalid credentials."})
    else:
        return render(request, "login.html")


def logout_view(request):
    logout(request)
    return render(request, "login.html", {"message": "Logged out."})


@login_required(login_url="customers:login")
def subscribe(request):
    try:
        if request.method == 'GET':
            if request.user.customer.sub:
                context = {"message": "You are already a subscriber!"}
                return render(request, "error.html", context)
            else:
                return render(request, "customers/subscribe.html")
        elif request.method == 'POST':
            money = request.POST['money']
            customer = request.user.customer
            if int(money) > customer.card_balance:
                return HttpResponse("Your account do not have enough money yet, please recharge.")
            else:
                customer.card_balance -= int(money)
                customer.sub = True
                customer.save()
                return HttpResponse("Congratulations! You are a subscriber now!")
        else:
            return render(request, "error.html", context={"message": "Method is not allowed!"})
    except:
        return render(request, "error.html", context={"message": "Please go to shop to recharge first!"})


@login_required(login_url="customers:login")
def shop(request):
    User()
    if request.method == 'GET':
        return render(request, "customers/shop.html")
    elif request.method == 'POST':
        cc = request.POST['cc']
        money = request.POST['money']
        phone = request.POST['phone']
        if 16 > len(cc) > 19:
            return render(request, "error.html", context={"message": "Check your credit card number length!"})
        try:
            customer = request.user.customer
            customer.credit_card = cc
            customer.card_balance += int(money)
            customer.save()
        except:
            customer = Customer()
            customer.username = request.user
            customer.credit_card = cc
            customer.card_balance = int(money)
            customer.save()
        return HttpResponseRedirect(reverse("customers:subscribe"))
    else:
        return render(request, "error.html", context={"message": "Method is not allowed!"})

articles/templates/articles/article.html
{% extends "base.html" %}

{% block body %}
<div class="article__content" style="padding-bottom: 30px">
    <div class="article__header">

        <h3 class="article__title">
            {{ article.title }}
        </h3>

        {% if article.author %}
        <div class="article__author">
            By <i>{{ article.author }}</i>
        </div>
        {% endif %}

        {% if article.date %}
        <div class="article__date">
            <i>{{ article.date }}</i>
        </div>
        {% endif %}
        <hr style="margin: 20px">
    </div>

    <div class="article__body">
        {{ article.free_text|safe }}
    </div>
    {% if article.pay_text != "None" %}
    {% if request.user.customer.sub %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <h5>Congratulations!</h5>
            <hr style="">The paywall has been broken down!
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="article__body">
            {{ article.pay_text|safe }}
        </div>
    {% else %}
    <hr>
    <div style="text-align: center;">
        <div style="">
            <h5 >TO READ THE FULL STORY</h5>
            {% if not request.user.is_authenticated %}
                <div class="row">
                    <div style="width: 50%; padding: 10px">
                        <button class="btn btn-primary btn-block" type="button">
                            <a href="{% url 'customers:shop' %}" style="color: #ffffff"><b>Subscribe</b></a>
                        </button>
                    </div>
                    <div style="width: 50%; padding: 10px">
                        <button class="btn btn-outline-dark btn-block" type="button">
                            <a href="{% url 'customers:login' %}" style="color: #000000"><b>Log in</b></a>
                        </button>
                    </div>
                </div>
            {% else %}
                <div style="width: 100%; padding: 20px">
                    <button class="btn btn-primary btn-block" type="button">
                        <a href="{% url 'customers:shop' %}" style="color: #ffffff"><b>Subscribe</b></a>
                    </button>
                </div>
            {% endif %}
        </div>
    </div>
    {% endif %}
    {% endif %}
</div>


{% endblock %}

articles/templates/articles/index.html
{% extends "base.html" %}


{% block body %}
	<div style="text-align: center; margin-top: 50px">
		<h3>Search for articles!</h3>
		<div class="col-md-8 offset-md-2 mt-5">
			<form action="{% url 'articles:search' %}" method="POST">
				{% csrf_token %}
				<div class="input-group mb-3" align="center">
					<input type="text" class="form-control" id="query" name="query" autofocus placeholder="Query...">
					<div class="input-group-append">
						<span class="input-group-text"><i class="fa fa-search"></i></span>
					</div>
				</div>
				<button class="btn btn-primary" id="search" style="margin-bottom: 3px; margin-top: 3px; margin-right: 10px; width: 20%"  type="submit" onclick="return handleChange()">Article Search</button>
				<a href="{% url 'articles:discovery' %}" style="margin-top: 3px; margin-bottom: 3px; margin-left: 10px; width: 20%" class="btn btn-primary">Discover</a>
			</form>
		</div>
	</div>
{% endblock %}

articles/templates/articles/results.html
{% extends "base.html" %}

{% block body %}
	<div style="text-align: center;">
		<div class="col-md-8 offset-md-2 mt-5">
			<form action="{% url 'articles:search' %}" method="POST">
				{% csrf_token %}
				<div class="input-group mb-3" align="center">
					<input type="text" class="form-control" name="query" autofocus value="{{ query }}">
					<div class="input-group-append">
						<button class="btn btn-success" type="submit">Article Search</button>
					</div>
				</div>
			</form>
		</div>
	</div>
	<hr>
	<div class="card-columns">
		{% for article in articles %}
				<div class="card">
					<blockquote class="blockquote mb-0 card-body">
						{% load poll_extras %}
						<h5 class="card-title">
							<a href="{% url 'articles:full_article' article.title|cut:" "%}" style="color:#000000;">
								{{ article.title }}
							</a>
						</h5>
						<p class="card-text">{{ article.brief|safe }}</p>
						{% if article.author %}
						<i>By: {{ article.author }}</i>
						{% endif %}
					</blockquote>
				</div>
		{% empty %}
		<p>No articles!</p>
		{% endfor %}
	</div>
{% endblock %}

customers/templates/customers/shop.html
{% extends "base.html" %}

{% block body %}
<div style="padding: 10%">
    <script>
        $(":input").inputmask();
        $("#phone").inputmask({"mask": "(999) 999-9999"});
    </script>
    <div>
        <h2 style="text-align: center; ">Input your credit card number and recharge!</h2>
        <hr style="padding: 20px">
        <form action="{% url 'customers:shop' %}" method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-7">
                    <label for="cc">Credit Card</label>
                    <input class="form-control" data-inputmask="'mask': '9999 9999 9999 9999'" id="cc" name="cc"
                           type="number"/>
                </div>

                <div class="col-5">
                    <label for="money">Charge Money</label>
                    <input class="form-control" id="money" name="money" type="number"/>
                </div>
            </div>
            <div class="form-row">
                <div class="col-12">
                    <label for="phone">Phone number</label>
                    <input class="form-control" id="phone" name="phone" type="tel"/>
                </div>
            </div>
            <div class="form-group row" style="padding-top: 20px">
                <div class="col-sm-10">
                    <button class="btn btn-primary" onclick="return handleChange2()" type="submit">Submit!</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

customers/templates/customers/subscribe.html
{% extends "base.html" %}

{% block body %}
<div style="margin-top: 50px">
    <script>
        $(document).ready(function () {

            $('#searchbar').focus();

            $('#donate-buttons').on('click', '.btn-donate', function (e) {
                e.preventDefault();
                $('.active').removeClass('active');
                $('#other-input').hide().siblings('#other').show();
                $(this).filter('.btn-donate').addClass("active");
                var value = $(this).data('impact');
                $(this).closest('div').find('p').text("" + value);
                $('#other-input').find('input').val('');
            });

            $('.btn-green').on('click', function () {
                var dollar;
                var input = $('#other-input').find('input').val();
                if (!input) {
                    dollar = $('.active').data('dollars');
                } else if ($.trim(input) === '' || isNaN(input)) {
                    // empty space leaves value = 'undefined'.
                    // Have to fix $.trim(input) == '' above so that it works.
                    console.log('Yes');
                    dollar = "Please enter a number.";
                } else {
                    dollar = input;
                }
                url = "{% url 'customers:subscribe' %}";
                data = {
                    money: dollar,
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                }
                $.ajax({
                    type: "POST",
                    url: "{% url 'customers:subscribe' %}",
                    data: {
                        "money": dollar,
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                    },
                    success: function (data) {
                        alert(data)
                        location.href="{% url 'customers:subscribe' %}"
                    },
                    failure: function (data) {
                        alert("Not success!")
                    },
                });
            });

            $('#other').on('click', function (e) {
                e.preventDefault();
                var buttons = $(this).parent('#donate-buttons');
                buttons.find('.active').removeClass('active');
                var other = $(this).hide().siblings('#other-input');
                other.show();
                other.find('input').focus();
                var oValue = other.find('input');
            });

        });
    </script>
    <script src="https://code.jquery.com/jquery-3.5.0.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>
    <div class="container theme-background-white main-body">
        <div class="col-md-12">
            <div class="row donate-bar">
                <div class="col-md-4 theme-blue">
                    <h3><strong>Donate to subscribe</strong></h3>
                    <hr>
                    <h4><strong>Your balance: </strong>{{ request.user.customer.card_balance }}</h4>
                </div>

                <div class="col-md-8" style="text-align: center">
                    <ul class="nav navbar-left donate-buttons" id="donate-buttons">
                        <li>
                            <button class="btn-donate active" data-dollars='25'>
                                $25
                            </button>
                        </li>
                        <li>
                            <button class="btn-donate" data-dollars='50'>
                                $50
                            </button>
                        </li>
                        <li>
                            <button class="btn-donate" data-dollars='100'>
                                $100
                            </button>
                        </li>
                        <li>
                            <button class="btn-donate" data-dollars='500'>
                                $500
                            </button>
                        </li>
                        <li id="other">
                            <button class="btn-donate-other" data-dollars='other' data-impact="Thank you!">
                                OTHER
                            </button>
                        </li>
                        <li id="other-input">
                            <!--<span>$</span>-->
                            <input data-impact="That’s great. Thank you!">
                        </li>
                    </ul>
                    <hr>
                    <button class="btn-green" data-target="#myModal" data-toggle="modal">
                        DONATE
                    </button>
                </div>
            </div><!--/.donate-bar-->
        </div><!-- /.col-md-12 -->
    </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta content="width=device-width, initial-scale=1" name="viewport">
        <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" crossorigin="anonymous"></script>
        <script type='text/javascript' src="https://rawgit.com/RobinHerbots/jquery.inputmask/3.x/dist/jquery.inputmask.bundle.js"></script>
        <!--Move everything after jquery-->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <link href="../static/S.png" rel="icon" type="image/x-icon"/>
        <link href="../static/footer.css" rel="stylesheet">
        <link rel="stylesheet" href="../static/app.css">
        <!--Must behind jQuery has been loaded-->
        <script src="../static/footer.js"></script>
        <script src="../static/app.js"></script>
        <title>News Market</title>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light border">
            <a class="navbar-brand" href="/">News Market</a>

            <button aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation"
                    class="navbar-toggler" data-target="#navbarNavDropdown" data-toggle="collapse" type="button">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="navbar-collapse collapse" id="navbarNavDropdown">
                <a class="navbar-item" href="/" style="padding-left: 10px">
                    <button class="btn btn-success" type="button">Home</button>
                </a>
                <a class="navbar-item" href="{% url 'articles:discovery' %}" style="padding-left: 10px">
                    <button class="btn btn-success" type="button">Article Plaza</button>
                </a>
                <a class="navbar-item" href="{% url 'customers:shop' %}" style="padding-left: 10px">
                    <button class="btn btn-success" type="button">Become Subscriber</button>
                </a>
                {% if request.user.is_staff %}
                <a class="navbar-item" href="{% url 'admin:index' %}" style="padding-left: 10px">
                    <button class="btn btn-success" type="button">Staff Dashboard</button>
                </a>
                {% endif %}
                {% if request.user.is_authenticated %}
                <div class="navbar-nav ml-auto">
                    <a class="nav-link" href="#" style="padding:1px">Hello! {{ request.user.username }}&nbsp</a>

                    <a class="nav-link" href="{% url 'customers:logout' %}" style="padding:1px">&nbspLog out</a>
                </div>
                {% else %}
                <div class="navbar-nav ml-auto">
                    <button class="btn btn-outline" type="button">
                        <a class="nav-link" href="{% url 'customers:login' %}" style="padding:1px"><b>Log in</b></a>
                    </button>
                </div>
            </div>
            {% endif %}
            </div>
        </nav>

        <main class="container p-6" style="padding: 0; margin-bottom: 20px">
            {% block body %}
            {% endblock %}
        </main>

        <footer class="site-footer bd-footer text-muted ">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 col-md-6">
                        <h6>About</h6>
                        <p class="text-justify">
                            In this platform, readers can search for articles arbitrarily or browse the latest articles in the article plaza. For editors, they can upload articles in a format of HTML, and also can set a paywall for any article. And readers can donate to become a subscriber to browse the full article section.
                        </p>
                    </div>

                    <div class="col-xs-6 col-md-3">
                        <h6>Categories</h6>
                        <ul class="footer-links">
                            <li><a href="/">Search</a></li>
                            <li><a href="{% url 'articles:discovery' %}">Find something new!</a></li>
                            <li><a href="{% url 'customers:shop' %}">Recharge for your account!</a></li>
                            <li><a href="{% url 'customers:subscribe' %}">Become a subscriber!</a></li>
                        </ul>
                    </div>

                    <div class="col-xs-6 col-md-3">
                        <h6>Quick Links</h6>
                        <ul class="footer-links">
                            <li><a href="mailto:wzywzy@mail.dlut.edu.cn">Feedback</a></li>
                            <li><a href="https://github.com/ESWZY">My Github</a></li>
                            <li>
                                <a href="https://github.com/ESWZY/cs50web-final-project">This</a>
                                <iframe frameborder="0"
                                        height="20px" scrolling="0"
                                        src="https://ghbtns.com/github-btn.html?user=ESWZY&repo=cs50web-final-project&type=star&count=true"
                                        style="margin-left: 2px; margin-bottom:-5px;"
                                        width="91px">
                                </iframe>
                            </li>
                        </ul>
                    </div>
                </div>
                <hr>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-sm-6 col-xs-12">
                        <p class="copyright-text">Copyright &copy; 2020 All Rights Reserved by
                            <a href="https://github.com/ESWZY">ESWZY</a>.
                        </p>
                    </div>

                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <ul class="social-icons">
                            <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
                            <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
    </body>
</html>

templates/error.html
{% extends "base.html" %}

{% block body %}
<div style="text-align: center; padding-top: 10%">
    <h1>Oops, {{ message }}</h1>

    <p style="font-size: 20px">Redirect to main page after <span id="totalSecond">5</span> seconds</p>
    <script language="javascript" type="text/javascript">
        var second = totalSecond.innerText;
        setInterval("redirect()", 1000);

        function redirect() {
            totalSecond.innerText = --second;
            if (second <= 0)
                location.href = '/';
        }
    </script>
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block body %}
<div align="left" width="40%" style="padding-right: 50%; margin-top: 50px">
	<h1>Login</h1>
    <form action="{% url 'customers:login' %}" method="post">
		{% csrf_token %}
		<label>Username</label>
		<div class="form-group">
			<input autocomplete="off" autofocus class="form-control" name="username" placeholder="Username" type="text"/>
		</div>
		<label>Password</label>
		<div class="form-group">
			<input type="password" name="password" class="form-control" placeholder="Password" />
		</div>
		{% if message %}
			<div style="color: red">
				{{ message }}
			</div>
		{% endif %}
		<button type="submit" class="btn btn-primary">Log In</button>
	</form>
</div>
{% endblock %}